admin_article:
    path:     /
    defaults: { _controller: "AppMainBundle:Article:index" }

admin_article_show:
    path:     /{id}/show
    defaults: { _controller: "AppMainBundle:Article:show" }

admin_article_new:
    path:     /new
    defaults: { _controller: "AppMainBundle:Article:new" }

admin_article_create:
    path:     /create
    defaults: { _controller: "AppMainBundle:Article:create" }
    methods:  POST

admin_article_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppMainBundle:Article:edit" }

admin_article_update:
    path:     /{id}/update
    defaults: { _controller: "AppMainBundle:Article:update" }
    methods:  [POST, PUT]

admin_article_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppMainBundle:Article:delete" }
    methods:  [POST, DELETE]
