admin_category:
    path:     /
    defaults: { _controller: "AppMainBundle:Category:index" }

admin_category_show:
    path:     /{id}/show
    defaults: { _controller: "AppMainBundle:Category:show" }

admin_category_new:
    path:     /new
    defaults: { _controller: "AppMainBundle:Category:new" }

admin_category_create:
    path:     /create
    defaults: { _controller: "AppMainBundle:Category:create" }
    methods:  POST

admin_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppMainBundle:Category:edit" }

admin_category_update:
    path:     /{id}/update
    defaults: { _controller: "AppMainBundle:Category:update" }
    methods:  [POST, PUT]

admin_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppMainBundle:Category:delete" }
    methods:  [POST, DELETE]
