admin_contact:
    path:     /
    defaults: { _controller: "AppMainBundle:Contact:index" }

admin_contact_show:
    path:     /{id}/show
    defaults: { _controller: "AppMainBundle:Contact:show" }

admin_contact_new:
    path:     /new
    defaults: { _controller: "AppMainBundle:Contact:new" }

admin_contact_create:
    path:     /create
    defaults: { _controller: "AppMainBundle:Contact:create" }
    methods:  POST

admin_contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppMainBundle:Contact:edit" }

admin_contact_update:
    path:     /{id}/update
    defaults: { _controller: "AppMainBundle:Contact:update" }
    methods:  [POST, PUT]

admin_contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppMainBundle:Contact:delete" }
    methods:  [POST, DELETE]
